### PR TITLE
update property in typings.json

### PR DESCRIPTION
**Pull request by justforuse**
latest typings change ambientDependencies to globalDependencies

### CODE REVIEW

**Comment by justforuse** [comment]
http://stackoverflow.com/questions/37484294/typings-install-gives-no-dependencies-as-output

**Comment by mgechev** [comment]
Thanks for the PR! The code for the last version of the book which uses types can be found here https://github.com/mgechev/getting-started-with-angular

**Comment by justforuse** [comment]
@mgechev  Thanks, and why the project that  you mentioned doesn't need typings.json? it does save much time, everything has no problem!

**Comment by mgechev** [comment]
https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Pull request merged**
